# Generated by Django 2.2.1 on 2019-08-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ip_range',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('device', 'platform')},
        ),
    ]
